# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/wen/Desktop/graduation_project/fjw/5_vga/greedy_snake.srcs/sources_1/ip/rom_end/rom_end.xci
# IP: The module: 'rom_end' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wen/Desktop/graduation_project/fjw/5_vga/greedy_snake.srcs/sources_1/ip/rom_end/rom_end_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_end'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/wen/Desktop/graduation_project/fjw/5_vga/greedy_snake.srcs/sources_1/ip/rom_end/rom_end.xci
# IP: The module: 'rom_end' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wen/Desktop/graduation_project/fjw/5_vga/greedy_snake.srcs/sources_1/ip/rom_end/rom_end_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_end'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
