# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/wen/Desktop/Greedy_snake/xilinx_snake/5_vga/greedy_snake.srcs/sources_1/ip/rom_start/rom_start.xci
# IP: The module: 'rom_start' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wen/Desktop/Greedy_snake/xilinx_snake/5_vga/greedy_snake.srcs/sources_1/ip/rom_start/rom_start_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_start'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/wen/Desktop/Greedy_snake/xilinx_snake/5_vga/greedy_snake.srcs/sources_1/ip/rom_start/rom_start.xci
# IP: The module: 'rom_start' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wen/Desktop/Greedy_snake/xilinx_snake/5_vga/greedy_snake.srcs/sources_1/ip/rom_start/rom_start_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_start'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
