# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/wen/Desktop/graduation_project/fjw/5_vga/greedy_snake.srcs/sources_1/ip/rom_speed/rom_speed.xci
# IP: The module: 'rom_speed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wen/Desktop/graduation_project/fjw/5_vga/greedy_snake.srcs/sources_1/ip/rom_speed/rom_speed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_speed'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/wen/Desktop/graduation_project/fjw/5_vga/greedy_snake.srcs/sources_1/ip/rom_speed/rom_speed.xci
# IP: The module: 'rom_speed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wen/Desktop/graduation_project/fjw/5_vga/greedy_snake.srcs/sources_1/ip/rom_speed/rom_speed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_speed'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
