# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/greedy_snake.xdc

# IP: ip/pll_clk/pll_clk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll_clk || ORIG_REF_NAME==pll_clk} -quiet] -quiet
